added checks and various optimizations (thx to aphector)

diff --git a/files/scripts/tvrename b/files/scripts/tvrename
--- a/files/scripts/tvrename
+++ b/files/scripts/tvrename
@@ -7,63 +7,75 @@
 # the resulting filename pattern looks like this:
 # [show].S[season]E[episode].[episode title].[file extension]
 
-FILENAME=$(basename $1 | sed 's/\(.*\)/\L\1/')  # lowercase filename
-EXT=${FILENAME##*.}  # determine filetype extension
-WGET=$(which wget)  # determine path to wget
-
 # usage help
-if [ "$#" != "1" ]; then
-    echo "Usage: $0 filename"
+if [ "$#" != "2" ]; then
+    echo "Usage: $0 filename new_path"
     exit 1
 fi
 
+# check if $1 is a regular file
+if [ ! -f "$1" ]; then
+    echo "$1 doesn't seem to be a regular file."
+    exit 1
+fi
+
+# check if $2 is a directory
+if [ ! -d "$2" ]; then
+    echo "$2 doesn't seem to be an existing directory."
+    exit 1
+fi
+
+FILENAME=$(basename "$1" | tr '[A-Z]' '[a-z]')  # lowercase filename
+#FILENAME=$(basename "$1" | sed 's/\(.*\)/\L\1/g')  # lowercase filename
+EXT=${FILENAME##*.}  # determine filetype extension
+WGET=$(which wget)  # determine path to wget
+
 # determine name of the show and set url
 case $FILENAME in
-    two.and.a.half.men.*)
+    two?and?a?half?men*)
 	SHOW="Two.And.A.Half.Men"
 	EPURL="http://epguides.com/TwoAndAHalfMen/"
 	;;
-    *big.bang.theory.*)
+    *big?bang?theory*)
 	SHOW="The.Big.Bang.Theory"
 	EPURL="http://epguides.com/BigBangTheory/"
 	;;
-    futurama.*)
+    futurama*)
 	SHOW="Futurama"
 	EPURL="http://epguides.com/Futurama/"
 	;;
-    *boondocks.*)
+    *boondocks*)
 	SHOW="The.Boondocks"
 	EPURL="http://epguides.com/Boondocks/"
 	;;
-    *boardwalk.empire.*)
+    *boardwalk?empire*)
 	SHOW="Boardwalk.Empire"
 	EPURL="http://epguides.com/BoardwalkEmpire/"
 	;;
-    breaking.bad.*)
+    breaking?bad*)
 	SHOW="Breaking.Bad"
 	EPURL="http://epguides.com/BreakingBad/"
 	;;
-    dexter.*)
-	SHOW="Dexter"
+    dexter*)
 	EPURL="http://epguides.com/Dexter/"
 	;;
-    american.dad.*)
+    american?dad*)
 	SHOW="American.Dad"
 	EPURL="http://epguides.com/AmericanDad/"
 	;;
-    family.guy.*)
+    family?guy*)
 	SHOW="Family.Guy"
 	EPURL="http://epguides.com/FamilyGuy/"
 	;;
-    *cleveland.show.*)
+    *cleveland?show*)
 	SHOW="The.Cleveland.Show"
 	EPURL="http://epguides.com/ClevelandShow/"
 	;;
-    the.simpsons.*)
+    the?simpsons*)
 	SHOW="The.Simpsons"
 	EPURL="http://epguides.com/Simpsons/"
 	;;
-    south.park.*)
+    south?park*)
 	SHOW="South.Park"
 	EPURL="http://epguides.com/SouthPark/"
 	;;
@@ -74,17 +86,26 @@ case $FILENAME in
 esac
 
 # extract numbers of season and episode from the filename
-SEASEP=$(echo $FILENAME | grep -oE 's[0-9]*e[0-9]*')
-SEASON=$(echo $SEASEP | grep -oE 's[0-9]*' | sed 's/s0\|s//g')
-EPISODE=$(echo $SEASEP | grep -oE 'e[0-9]*' | sed 's/e//g')
+SEASEP=$(echo $FILENAME | grep -oE '(s|\W)[0-9]+(e|x)[0-9]+')
+
+if [ -n $SEASEP ]; then
+    SEASON=$(echo $SEASEP | grep -oP '[0-9]+(?=x|e)' | sed 's/^0\+//g')
+    EPISODE=$(echo $SEASEP | grep -oP '(?<=x|e)[0-9]+')
+else
+    echo "Could not find a valid season/episode pattern."
+    exit 1
+fi
+
+# prefix single digit episodes with a "0" (e.g.: E03)
+EPISODE=$(printf '%02d' $((10#$EPISODE)))
 
 # fetch episode list and save to file
 LIST="/tmp/$SHOW.list"
 $WGET -q $EPURL -O $LIST
 
 # regex episode title to taste
-EPTIT=$(cat $LIST | grep -e "\s$SEASON-$EPISODE" | \
-    sed -r "s/^.*[0-9]'>//;\
+EPTIT=$(cat $LIST | grep -E "\s$SEASON-$EPISODE" | \
+    sed -r "s/^[^>]*[0-9]*'>//;\
 	    s/<\/a.*$//;\
 	    s/\b(.)/\U\1/g;\
 	    s/[,;:\?\!]//g;\
@@ -93,13 +114,14 @@ EPTIT=$(cat $LIST | grep -e "\s$SEASON-$EPISODE" | \
 	    s/'(.)/'\L\1/g;\
 	    s/\ /./g")
 
-# prefix single digit seasons with a 0 (e.g.: S05)
-if [ "`echo $SEASON | wc -m`" == "2" ] ; then SEASON="0$SEASON"; fi
+# prefix single digit seasons with a "0" (e.g.: S05)
+SEASON=$(printf '%02d' $((10#$SEASON)))
 
 # concatenate the filename pattern
-NEWTIT="$SHOW.S$SEASON"E"$EPISODE.$EPTIT.$EXT"
+NEWTIT="$SHOW.S${SEASON}E$EPISODE.$EPTIT.$EXT"
 
-echo $NEWTIT
+# move and rename the file
+mv "$1" "$2"/$NEWTIT
 
 # clean up
 rm $LIST
